### ISSUE TITLE
hardware?

### ISSUE THREAD

**Issue by csloz** [UKSFM99/W203-canbus#1]
Suggest fill in some details on hardware interfacing?

How do you get at the canbus?
What chipset are you using?

etc

**Comment by rnd-ash** [comment]
https://github.com/UKSFM99/W203-canbus/blob/master/setup.png -> Setup diagram for breadboard

I'm using the sparkfun canbus shield v1.2 to read canbus.

In regards to wiring, I have ran some wires from underneath the drivers steering wheel area under the center console and up into the center console bin (which took about 3 hours to do). From there I simply plug the canbus shield into the wires and everything is ready. Hope this helps

**Comment by csloz** [comment]
Thank you, yes, helpful!

I'll see if i can find some details on the wiring on the car side, may be an easier way to get at the bus.  Is it exposed on the OBDII port, or did you cut in elsewhere?  

I will need to dig into my W209 docs..

**Comment by rnd-ash** [comment]
unfortunately no. canbus B is not exposed from odb2. I'm assuming you have a w203 as well. in which case if you take the panel off where the odb2 connector is connected to (the entire black panel with 3 screws at the front), you should be able to see the hub for canB

**Comment by csloz** [comment]
I have a C219/W219  (CLS350 2006 model) - COMAND APS NTG1, with a MOST bus.

W203 also used the same hardware I think, so should be comparable if not the same.  

Mine is the Harman Kardon one, so a little more painful!
NTG1 + CD Changer with the DVD in the back for maps.

**Comment by rnd-ash** [comment]
so yeah should be the same then. hopefully if you follow my hardware setup I can have another tester :D
